# Site settings
title: Omid Dehghani
description: Death is what reminds me of life.
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://guftall.ir"  # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: guftall
user_description: A silent man
user_title: Software Engineering STUDENT
email: omid@guftall.ir
twitter_username: omid_deh
github_username:  guftall
# gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
